// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8qj2wUQwP6iRl9SPlfJjesUXH_wc8k5E',
    appId: '1:517915885966:web:6447626cba697053a0e4df',
    messagingSenderId: '517915885966',
    projectId: 'muzaico-bb279',
    authDomain: 'muzaico-bb279.firebaseapp.com',
    storageBucket: 'muzaico-bb279.firebasestorage.app',
    measurementId: 'G-24HDNF9BX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcF6Y8WmnCarosJmVfvUOTg551Kh-kyqA',
    appId: '1:517915885966:android:9fa94dc3d88afae1a0e4df',
    messagingSenderId: '517915885966',
    projectId: 'muzaico-bb279',
    storageBucket: 'muzaico-bb279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc1Zdi98Ejmyne9c7f_aqE6ygtD22m1vs',
    appId: '1:517915885966:ios:f80d2efb0b954d9ba0e4df',
    messagingSenderId: '517915885966',
    projectId: 'muzaico-bb279',
    storageBucket: 'muzaico-bb279.firebasestorage.app',
    androidClientId: '517915885966-0atn55stsogop7fuvt7in7041ak3ubuk.apps.googleusercontent.com',
    iosClientId: '517915885966-c72l8deeggr8r9slke2e7j2h7j8b7nn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.muzaiko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc1Zdi98Ejmyne9c7f_aqE6ygtD22m1vs',
    appId: '1:517915885966:ios:f80d2efb0b954d9ba0e4df',
    messagingSenderId: '517915885966',
    projectId: 'muzaico-bb279',
    storageBucket: 'muzaico-bb279.firebasestorage.app',
    androidClientId: '517915885966-0atn55stsogop7fuvt7in7041ak3ubuk.apps.googleusercontent.com',
    iosClientId: '517915885966-c72l8deeggr8r9slke2e7j2h7j8b7nn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.muzaiko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8qj2wUQwP6iRl9SPlfJjesUXH_wc8k5E',
    appId: '1:517915885966:web:1d4b3512520bf110a0e4df',
    messagingSenderId: '517915885966',
    projectId: 'muzaico-bb279',
    authDomain: 'muzaico-bb279.firebaseapp.com',
    storageBucket: 'muzaico-bb279.firebasestorage.app',
    measurementId: 'G-GM26C99VD7',
  );
}
